/**
 * Demo corpus for Indulge, set in the Mumbai–Thane belt.
 *
 * Coordinates are real and spread over ~20 km so radius filtering and the
 * distance factor in the ranking produce visibly different results rather than
 * a tie. Prices are deliberately varied within each category so the price
 * factor also separates the options.
 */

export const BUSINESSES = [
  {
    key: 'grandOrchid',
    businessName: 'The Grand Orchid Hotel',
    email: 'ops@grandorchid.in',
    businessType: 'hotel',
    phone: '+91 98200 11001',
    location: { address: 'Eastern Express Hwy', city: 'Thane', pincode: '400603', coordinates: [72.9781, 19.2183] },
  },
  {
    key: 'seasons',
    businessName: 'Seasons Banquet & Convention',
    email: 'events@seasonsbanquet.in',
    businessType: 'banquet_venue',
    phone: '+91 98200 11002',
    location: { address: 'Ghodbunder Road', city: 'Thane', pincode: '400607', coordinates: [72.9563, 19.2519] },
  },
  {
    key: 'spiceRoute',
    businessName: 'Spice Route Caterers',
    email: 'hello@spiceroute.co.in',
    businessType: 'caterer',
    phone: '+91 98200 11003',
    location: { address: 'LBS Marg, Mulund', city: 'Mumbai', pincode: '400080', coordinates: [72.9560, 19.1726] },
  },
  {
    key: 'blueBay',
    businessName: 'Blue Bay Resort',
    email: 'reservations@bluebay.in',
    businessType: 'resort',
    phone: '+91 98200 11004',
    location: { address: 'Yeoor Hills', city: 'Thane', pincode: '400610', coordinates: [72.9330, 19.2400] },
  },
  {
    key: 'kalpataru',
    businessName: 'Kalpataru Events Co.',
    email: 'desk@kalpataruevents.in',
    businessType: 'event_organizer',
    phone: '+91 98200 11005',
    location: { address: 'Powai Plaza', city: 'Mumbai', pincode: '400076', coordinates: [72.9051, 19.1176] },
  },
  {
    key: 'coastal',
    businessName: 'Coastal Kitchen & Grill',
    email: 'manager@coastalkitchen.in',
    businessType: 'restaurant',
    phone: '+91 98200 11006',
    location: { address: 'Hiranandani Estate', city: 'Thane', pincode: '400607', coordinates: [72.9430, 19.2620] },
  },
  {
    key: 'silverline',
    businessName: 'Silverline Hospitality Rentals',
    email: 'rentals@silverline.in',
    businessType: 'other',
    phone: '+91 98200 11007',
    location: { address: 'Wagle Estate', city: 'Thane', pincode: '400604', coordinates: [72.9630, 19.1990] },
  },
  {
    key: 'meridian',
    businessName: 'Meridian Business Hotel',
    email: 'front@meridianhotel.in',
    businessType: 'hotel',
    phone: '+91 98200 11008',
    location: { address: 'Vashi Sector 17', city: 'Navi Mumbai', pincode: '400703', coordinates: [73.0071, 19.0760] },
  },
];

const img = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=70`;

export const RESOURCES = [
  // ---- Banquet spaces: same category, deliberately different price/capacity/distance ----
  {
    owner: 'seasons',
    title: 'Crystal Grand Ballroom — 500 guests',
    category: 'banquet_space',
    description:
      'Pillarless ballroom with a 20ft stage, in-house lighting rig and dedicated service entry. Suited to weddings, conferences and product launches.',
    highlights: ['Pillarless 6,500 sq ft floor', 'In-house stage & lighting', 'Separate service entrance', 'Valet parking for 120 cars'],
    totalQuantity: 1,
    unit: 'unit',
    capacity: 500,
    pricing: { basePrice: 85000, priceUnit: 'per_day', minRentalPeriodHours: 6 },
    conditions: 'Outside catering permitted with a 15% royalty. Decor teardown by 11pm.',
    tags: ['wedding', 'conference', 'AC', 'stage', 'valet'],
    images: [img('1519167758481-83f550bb49b3'), img('1464366400600-7168b8af9bc3')],
  },
  {
    owner: 'grandOrchid',
    title: 'Orchid Hall — 250 guests',
    category: 'banquet_space',
    description:
      'Mid-sized banquet hall on the second floor with natural light, an attached pre-function area and hotel catering on call.',
    highlights: ['3,200 sq ft', 'Attached pre-function foyer', 'Hotel kitchen on site', 'Natural daylight'],
    totalQuantity: 1,
    unit: 'unit',
    capacity: 250,
    pricing: { basePrice: 42000, priceUnit: 'per_day', minRentalPeriodHours: 4 },
    conditions: 'In-house catering mandatory. Minimum 100 covers.',
    tags: ['conference', 'AC', 'daylight', 'wedding'],
    images: [img('1519225421980-715cb0215aed'), img('1519167758481-83f550bb49b3')],
  },
  {
    owner: 'blueBay',
    title: 'Poolside Lawn — 300 guests',
    category: 'banquet_space',
    description:
      'Open-air lawn beside the infinity pool, with a covered bar counter and string lighting. Popular for sangeets and cocktail receptions.',
    highlights: ['Open-air with pool backdrop', 'Covered bar counter', 'String lighting included', 'Generator backup'],
    totalQuantity: 1,
    unit: 'unit',
    capacity: 300,
    pricing: { basePrice: 55000, priceUnit: 'per_day', minRentalPeriodHours: 5 },
    conditions: 'Music must stop at 10pm per local noise rules. Monsoon dates need a tent add-on.',
    tags: ['outdoor', 'lawn', 'cocktail', 'sangeet'],
    images: [img('1571896349842-33c89424de2d'), img('1505236858219-8359eb29e329')],
  },
  {
    owner: 'meridian',
    title: 'Meridian Conference Room — 80 seats',
    category: 'banquet_space',
    description:
      'Boardroom-style conference space with built-in projection, video-conferencing and tiered seating.',
    highlights: ['Built-in 4K projector', 'VC-ready with ceiling mics', 'Tiered seating', 'High-speed leased line'],
    totalQuantity: 2,
    unit: 'unit',
    capacity: 80,
    pricing: { basePrice: 18000, priceUnit: 'per_day', minRentalPeriodHours: 3 },
    conditions: 'Tea/coffee service billed separately per head.',
    tags: ['conference', 'AC', 'projector', 'corporate'],
    images: [img('1497366754035-f200968a6e72'), img('1517457373958-b7bdd4587205')],
  },

  // ---- Furniture: fungible stock, exercises partial allocation ----
  {
    owner: 'silverline',
    title: 'Chiavari Banquet Chairs (gold)',
    category: 'furniture',
    description:
      'Gold Chiavari chairs with ivory cushions. Stackable, delivered in lots of 25 with protective covers.',
    highlights: ['Gold finish, ivory cushion', 'Delivered in lots of 25', 'Cleaned between hires', 'Stackable'],
    totalQuantity: 300,
    unit: 'unit',
    capacity: null,
    pricing: { basePrice: 45, priceUnit: 'per_unit', minRentalPeriodHours: 8 },
    conditions: 'Damage billed at ₹1,800 per chair. Minimum hire 50 chairs.',
    tags: ['chairs', 'wedding', 'banquet', 'gold'],
    images: [img('1517248135467-4c7edcad34c4'), img('1519167758481-83f550bb49b3')],
  },
  {
    owner: 'kalpataru',
    title: 'Round Banquet Tables (6ft, seats 10)',
    category: 'furniture',
    description: 'Six-foot round tables with folding legs, supplied with white or ivory floor-length linen.',
    highlights: ['Seats 10 comfortably', 'Linen included', 'Folding legs for transport', 'Stain-treated tops'],
    totalQuantity: 60,
    unit: 'unit',
    capacity: 10,
    pricing: { basePrice: 320, priceUnit: 'per_unit', minRentalPeriodHours: 8 },
    conditions: 'Linen laundering included. Minimum hire 10 tables.',
    tags: ['tables', 'banquet', 'linen'],
    images: [img('1522413452208-996ff3f3e740'), img('1517248135467-4c7edcad34c4')],
  },

  // ---- AV equipment ----
  {
    owner: 'kalpataru',
    title: 'Line Array PA System + 2 Technicians',
    category: 'av_equipment',
    description:
      'Eight-box line array with subs, digital desk and monitor wedges. Comes with two technicians for setup, soundcheck and teardown.',
    highlights: ['8-box line array + 4 subs', 'Digital mixing desk', '2 technicians included', 'Covers up to 800 guests'],
    totalQuantity: 3,
    unit: 'unit',
    capacity: 800,
    pricing: { basePrice: 28000, priceUnit: 'per_day', minRentalPeriodHours: 6 },
    conditions: 'Power backup to be arranged by the hirer. Setup needs 4 hours lead time.',
    tags: ['sound', 'PA', 'technician', 'concert'],
    images: [img('1493225457124-a3eb161ffa5f'), img('1516280440614-37939bbacd81')],
  },
  {
    owner: 'silverline',
    title: 'LED Wall 12ft × 8ft (P3 indoor)',
    category: 'av_equipment',
    description: 'P3 indoor LED video wall with processor and rigging truss. Crew included for install.',
    highlights: ['P3 pixel pitch, indoor', 'Processor + spare panels', 'Rigging truss included', 'Install crew provided'],
    totalQuantity: 2,
    unit: 'unit',
    capacity: null,
    pricing: { basePrice: 35000, priceUnit: 'per_day', minRentalPeriodHours: 8 },
    conditions: 'Requires 3-phase power at the venue. Not suitable for open-air daytime use.',
    tags: ['LED', 'screen', 'video', 'stage'],
    images: [img('1540575467063-178a50c2df87'), img('1492684223066-81342ee5ff30')],
  },
  {
    owner: 'meridian',
    title: 'Portable Projector + Screen Kit',
    category: 'av_equipment',
    description: 'Compact 5000-lumen projector with tripod screen, HDMI/USB-C inputs and clicker.',
    highlights: ['5000 lumens', '8ft tripod screen', 'HDMI + USB-C', 'Self-setup in 10 minutes'],
    totalQuantity: 6,
    unit: 'unit',
    capacity: 100,
    pricing: { basePrice: 2500, priceUnit: 'per_day', minRentalPeriodHours: 4 },
    conditions: 'Self-pickup available. Late return billed at a full day.',
    tags: ['projector', 'screen', 'corporate', 'portable'],
    images: [img('1517457373958-b7bdd4587205'), img('1526666923127-b2970f64b422')],
  },

  // ---- Kitchen capacity ----
  {
    owner: 'coastal',
    title: 'Commercial Kitchen — Off-peak Hours',
    category: 'kitchen_capacity',
    description:
      'FSSAI-licensed commercial kitchen available 11pm–8am. Four burner ranges, combi oven, blast chiller and prep counters.',
    highlights: ['FSSAI licensed', 'Combi oven + blast chiller', '4 heavy-duty ranges', 'Cold storage access'],
    totalQuantity: 1,
    unit: 'hour',
    capacity: 400,
    pricing: { basePrice: 1800, priceUnit: 'per_hour', minRentalPeriodHours: 4 },
    conditions: 'Hirer must hold a valid FSSAI licence. Deep clean on exit is mandatory.',
    tags: ['kitchen', 'FSSAI', 'commercial', 'night'],
    images: [img('1556910103-1c02745aae4d'), img('1414235077428-338989a2e8c0')],
  },
  {
    owner: 'spiceRoute',
    title: 'Bulk Prep Kitchen + 6 Cooks',
    category: 'kitchen_capacity',
    description:
      'Production kitchen geared for 1,000+ covers with a six-person crew. Ideal for overflow during peak wedding dates.',
    highlights: ['1,000+ cover capacity', 'Crew of 6 included', 'Bulk steamers and cauldrons', 'Packing area attached'],
    totalQuantity: 1,
    unit: 'unit',
    capacity: 1200,
    pricing: { basePrice: 32000, priceUnit: 'per_day', minRentalPeriodHours: 8 },
    conditions: 'Raw material sourced by the hirer. Menu to be shared 48 hours in advance.',
    tags: ['kitchen', 'bulk', 'crew', 'catering'],
    images: [img('1466637574441-749b8f19452f'), img('1556910103-1c02745aae4d')],
  },

  // ---- Parking ----
  {
    owner: 'grandOrchid',
    title: 'Covered Parking Bays (Basement)',
    category: 'parking',
    description: 'Basement parking bays with 24×7 security and CCTV, available for event overflow.',
    highlights: ['Covered basement', 'CCTV + security', 'Height clearance 2.4m', 'Direct lift access'],
    totalQuantity: 80,
    unit: 'slot',
    capacity: null,
    pricing: { basePrice: 120, priceUnit: 'per_unit', minRentalPeriodHours: 4 },
    conditions: 'No overnight parking beyond event hours without prior approval.',
    tags: ['parking', 'covered', 'CCTV', 'basement'],
    images: [img('1506521781263-d8422e82f27a'), img('1590674899484-d5640e854abe')],
  },
  {
    owner: 'meridian',
    title: 'Open Parking Ground — 150 cars',
    category: 'parking',
    description: 'Levelled open ground adjacent to the hotel, with marked bays and two attendants.',
    highlights: ['150 marked bays', '2 attendants included', 'Floodlit after dark', 'Coach access'],
    totalQuantity: 150,
    unit: 'slot',
    capacity: null,
    pricing: { basePrice: 70, priceUnit: 'per_unit', minRentalPeriodHours: 4 },
    conditions: 'Vehicles parked at owner risk. Monsoon surface may be soft.',
    tags: ['parking', 'open', 'attendant'],
    images: [img('1590674899484-d5640e854abe'), img('1506521781263-d8422e82f27a')],
  },

  // ---- Vehicles ----
  {
    owner: 'blueBay',
    title: 'Guest Shuttle Bus (32-seater)',
    category: 'vehicle',
    description: 'AC 32-seater coach with driver, used for guest transfers between venue and hotels.',
    highlights: ['32 seats, AC', 'Driver included', 'Luggage bay', 'All-India permit'],
    totalQuantity: 2,
    unit: 'unit',
    capacity: 32,
    pricing: { basePrice: 9500, priceUnit: 'per_day', minRentalPeriodHours: 6 },
    conditions: 'Fuel and tolls billed at actuals. 250 km/day included.',
    tags: ['bus', 'shuttle', 'transfer', 'AC'],
    images: [img('1544620347-c4fd4a3d5957'), img('1464219222984-216ebffaaf85')],
  },
  {
    owner: 'silverline',
    title: 'Refrigerated Van (1.5 ton)',
    category: 'vehicle',
    description: 'Temperature-controlled van for moving prepared food and floral stock between sites.',
    highlights: ['-5°C to 8°C range', '1.5 ton payload', 'Driver included', 'Insulated loading curtain'],
    totalQuantity: 3,
    unit: 'unit',
    capacity: null,
    pricing: { basePrice: 4200, priceUnit: 'per_day', minRentalPeriodHours: 4 },
    conditions: 'Cleaning charge of ₹800 applies after raw meat transport.',
    tags: ['van', 'refrigerated', 'logistics', 'cold-chain'],
    images: [img('1586339949916-3e9457bef6d3'), img('1519003722824-194d4455a60c')],
  },

  // ---- Staff ----
  {
    owner: 'spiceRoute',
    title: 'Trained Banquet Service Staff',
    category: 'staff',
    description:
      'Uniformed service staff experienced in plated and buffet service, deployable at short notice.',
    highlights: ['Uniform included', 'Plated & buffet trained', 'Min 4 staff per booking', 'Supervisor on request'],
    totalQuantity: 40,
    unit: 'unit',
    capacity: null,
    pricing: { basePrice: 1400, priceUnit: 'per_unit', minRentalPeriodHours: 6 },
    conditions: 'Meals to be provided by the hirer for shifts over 6 hours.',
    tags: ['staff', 'service', 'banquet', 'uniformed'],
    images: [img('1414235077428-338989a2e8c0'), img('1600891964092-4316c288032e')],
  },
  {
    owner: 'kalpataru',
    title: 'Event Crew — Setup & Teardown',
    category: 'staff',
    description: 'General crew for staging, rigging assistance, furniture layout and post-event clearing.',
    highlights: ['Setup and teardown', 'Safety-trained for rigging assist', 'Min 6 crew', 'Night shifts available'],
    totalQuantity: 25,
    unit: 'unit',
    capacity: null,
    pricing: { basePrice: 1100, priceUnit: 'per_unit', minRentalPeriodHours: 6 },
    conditions: 'Overtime beyond 8 hours billed at 1.5×.',
    tags: ['crew', 'setup', 'teardown', 'labour'],
    images: [img('1522071820081-009f0129c71c'), img('1552664730-d307ca884978')],
  },
  {
    owner: 'coastal',
    title: 'Bar Counter + 2 Bartenders',
    category: 'staff',
    description: 'Portable bar counter with two experienced bartenders. Glassware and ice included.',
    highlights: ['Portable 8ft counter', '2 bartenders', 'Glassware & ice included', 'Mocktail menu available'],
    totalQuantity: 4,
    unit: 'unit',
    capacity: 200,
    pricing: { basePrice: 12000, priceUnit: 'per_event', minRentalPeriodHours: 5 },
    conditions: 'Liquor licence is the hirer’s responsibility. Alcohol not supplied.',
    tags: ['bar', 'bartender', 'cocktail', 'service'],
    images: [img('1543007630-9710e4a00a20'), img('1470337458703-46ad1756a187')],
  },
];
