import Transaction from '../models/Transaction.js';
import Booking from '../models/Booking.js';
import ProcurementOrder from '../models/ProcurementOrder.js';
import { HttpError } from '../middleware/error.middleware.js';

/**
 * Builds the canonical, immutable receipt object for a single transaction.
 * Enforces strict authorization: only seeker, provider, or admin may access.
 */
export async function getTransactionReceiptData(transactionId, user, { isAdmin = false } = {}) {
  const transaction = await Transaction.findById(transactionId)
    .populate('booking')
    .populate('payer', 'businessName email phone location userType')
    .populate('payee', 'businessName email phone location userType');

  if (!transaction) {
    throw new HttpError(404, 'Transaction not found.');
  }

  // Check authorization
  if (!isAdmin && user) {
    const payerId = String(transaction.payer?._id || transaction.payer);
    const payeeId = String(transaction.payee?._id || transaction.payee);
    const userId = String(user._id);

    if (userId !== payerId && userId !== payeeId) {
      throw new HttpError(403, 'Access denied: You are not authorized to view this receipt.');
    }
  }

  // Load resource details from booking if present
  let resource = null;
  let booking = transaction.booking;
  if (booking && typeof booking === 'object') {
    if (booking.resource && typeof booking.resource !== 'object') {
      const ResourceModel = (await import('../models/Resource.js')).default;
      resource = await ResourceModel.findById(booking.resource).select('title category pricing unit').lean();
    } else {
      resource = booking.resource;
    }
  }

  const receiptNumber =
    transaction.reconciliationRef ||
    `REC-TXN-${String(transaction._id).slice(-8).toUpperCase()}`;

  const bookingId = booking?._id ? String(booking._id) : (booking ? String(booking) : null);
  const bookingNumber = booking?.bookingNumber || (bookingId ? `BK-${bookingId.slice(-6).toUpperCase()}` : null);

  const bookingPeriod = {
    startDate: booking?.startDateTime || booking?.startDate || null,
    endDate: booking?.endDateTime || booking?.endDate || null,
  };

  const receipt = {
    receiptNumber,
    transactionId: String(transaction._id),
    bookingId,
    bookingNumber,
    payerBusiness: {
      id: transaction.payer?._id ? String(transaction.payer._id) : null,
      name: transaction.payer?.businessName || 'Payer Business',
      email: transaction.payer?.email || null,
      phone: transaction.payer?.phone || null,
      city: transaction.payer?.location?.city || null,
    },
    providerBusiness: {
      id: transaction.payee?._id ? String(transaction.payee._id) : null,
      name: transaction.payee?.businessName || 'Provider Business',
      email: transaction.payee?.email || null,
      phone: transaction.payee?.phone || null,
      city: transaction.payee?.location?.city || null,
    },
    resource: {
      id: resource?._id ? String(resource._id) : null,
      title: resource?.title || 'Hospitality Resource / Service',
      category: resource?.category || 'hospitality',
    },
    quantity: booking?.quantity || booking?.requestedQuantity || 1,
    bookingPeriod,
    amount: transaction.amount,
    currency: 'INR',
    paymentMethod: transaction.paymentMethod || 'Simulated Transfer',
    paymentStatus: transaction.status,
    paymentTimestamp: transaction.paidAt || transaction.createdAt,
    notice: 'Demo / Simulated Payment Receipt',
    receiptType: 'Demo / Simulated Payment Receipt',
    disclaimer:
      'This is a demo / simulated payment receipt generated by Indulge for test and marketplace simulation purposes. This is not a tax invoice under GST laws.',
    isSimulated: true,
    isDemo: true,
  };

  return receipt;
}

/**
 * Builds the canonical grouped receipt object for a multi-provider procurement order.
 * Enforces strict authorization and confidentiality:
 * - Seeker and Admin see the overall grouped total and breakdown.
 * - Provider A sees only Provider A's child details and subtotal, never Provider B's amounts.
 * - Unrelated businesses are rejected with 403.
 */
export async function getProcurementReceiptData(procurementOrderId, user, { isAdmin = false } = {}) {
  const order = await ProcurementOrder.findById(procurementOrderId)
    .populate('seeker', 'businessName email phone location')
    .populate({
      path: 'childBookings',
      populate: [
        { path: 'provider', select: 'businessName email phone location' },
        { path: 'resource', select: 'title category' },
      ],
    })
    .populate('childTransactions');

  if (!order) {
    throw new HttpError(404, 'Procurement order not found.');
  }

  const userId = user ? String(user._id) : null;
  const isSeeker = userId && String(order.seeker?._id || order.seeker) === userId;

  // Check if caller is one of the providers
  const callerProviderBooking = order.childBookings?.find(
    (b) => String(b.provider?._id || b.provider) === userId
  );

  if (!isAdmin && !isSeeker && !callerProviderBooking) {
    throw new HttpError(403, 'Access denied: You are not authorized to view this procurement receipt.');
  }

  const receiptNumber = `REC-PO-${order.orderNumber || String(order._id).slice(-6).toUpperCase()}`;

  // If caller is an individual provider (not seeker, not admin):
  // Privacy rule: Provider A in split procurement must not see Provider B financial details.
  if (!isAdmin && !isSeeker && callerProviderBooking) {
    const b = callerProviderBooking;
    const providerAmount = b.agreedPrice || b.quotedPrice || 0;
    const childTxn = (order.childTransactions || []).find(
      (t) => String(t.booking) === String(b._id) || String(t.payee) === userId
    );

    return {
      receiptNumber: `${receiptNumber}-P${String(b._id).slice(-4).toUpperCase()}`,
      procurementOrderId: String(order._id),
      orderNumber: order.orderNumber,
      isIndividualProviderView: true,
      payerBusiness: {
        id: order.seeker?._id ? String(order.seeker._id) : null,
        name: order.seeker?.businessName || 'Procurement Buyer',
      },
      providerBusiness: {
        id: String(b.provider?._id || b.provider),
        name: b.provider?.businessName || 'Your Business',
      },
      allocation: {
        bookingId: String(b._id),
        resourceTitle: b.resource?.title || 'Allocated Resource',
        quantity: b.requestedQuantity,
        amount: providerAmount,
        transactionId: childTxn ? String(childTxn._id) : null,
      },
      totalAmount: providerAmount,
      currency: 'INR',
      paymentStatus: 'paid',
      paymentTimestamp: order.createdAt,
      notice: 'Demo / Simulated Payment Receipt',
      disclaimer:
        'This is a demo / simulated allocation payment receipt. Private to your provider share. Not a GST tax invoice.',
      isSimulated: true,
    };
  }

  // Seeker or Admin: full grouped receipt
  const providersBreakdown = (order.childBookings || []).map((b, idx) => {
    const childTxn = (order.childTransactions || []).find((t) => String(t.booking) === String(b._id));
    return {
      index: idx + 1,
      bookingId: String(b._id),
      transactionId: childTxn ? String(childTxn._id) : null,
      providerId: b.provider?._id ? String(b.provider._id) : null,
      providerName: b.provider?.businessName || `Provider #${idx + 1}`,
      resourceTitle: b.resource?.title || 'Resource Allocation',
      quantity: b.requestedQuantity || 0,
      amount: b.agreedPrice || b.quotedPrice || 0,
    };
  });

  return {
    receiptNumber,
    procurementOrderId: String(order._id),
    orderNumber: order.orderNumber,
    isIndividualProviderView: false,
    payerBusiness: {
      id: order.seeker?._id ? String(order.seeker._id) : null,
      name: order.seeker?.businessName || 'Procurement Buyer',
      email: order.seeker?.email || null,
      phone: order.seeker?.phone || null,
      city: order.seeker?.location?.city || null,
    },
    providers: providersBreakdown,
    items: providersBreakdown,
    totalAmount: order.totalPrice,
    currency: 'INR',
    paymentMethod: 'Simulated Instant Settlement',
    paymentStatus: order.status === 'confirmed' ? 'paid' : order.status,
    paymentTimestamp: order.createdAt,
    notice: 'Demo / Simulated Payment Receipt',
    disclaimer:
      'This is a demo / simulated payment receipt for multi-provider grouped procurement. This is not a tax invoice under GST laws.',
    isSimulated: true,
  };
}
